name: Nightly Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-26
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          chmod +x dist/build.sh
          ./dist/build.sh

      - name: Install create-dmg
        run: brew install create-dmg

      - name: Create DMG
        run: |
          chmod +x dist/deploy-to-dmg.sh
          ./dist/deploy-to-dmg.sh

      - name: Update "Nightly" Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          name: "InstantSpaceSwitcher Nightly"
          prerelease: true
          body: |
            Latest automatic build from the main branch. Might be broken.
          files: |
            build/InstantSpaceSwitcher-*.dmg
